// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package projectsweb

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NewProjectForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"new_project_form\" hx-post=\"/projects/create\" hx-target=\"#project_list\" hx-swap=\"beforebegin\" hx-on::after-request=\"if (event.detail.target.id === 'project_list') project_modal.close()\"><fieldset class=\"fieldset flex flex-col\"><legend class=\"fieldset-legend\">Project name</legend> <input name=\"name\" type=\"text\" class=\"input validator w-full\" placeholder=\"NER\" minlength=\"3\" maxlength=\"100\" required><p class=\"validator-hint\">Must be between 3 and 100 in length</p><legend class=\"fieldset-legend\">Project description</legend> <textarea name=\"description\" type=\"text\" class=\"textarea validator w-full\" minlength=\"10\" maxlength=\"500\" placeholder=\"NER for bank cheques\" required></textarea><p class=\"validator-hint\">Must be between 10 and 500 in length</p></fieldset><fieldset class=\"fieldset grid grid-cols-3 gap-4 mt-4\"><div><legend class=\"fieldset-legend\">CPU limit</legend> <input name=\"cpu_limit\" type=\"number\" class=\"input validator input w-full\" min=\"1\" placeholder=\"1\" required><p class=\"validator-hint\">>= 1 </p></div><div><legend class=\"fieldset-legend\">RAM limit</legend> <input name=\"ram_limit\" type=\"number\" class=\"input validator w-full\" min=\"1\" placeholder=\"1\" required value><p class=\"validator-hint\">>= 1 </p></div><div><legend class=\"fieldset-legend\">Storage limit</legend> <input name=\"storage_limit\" type=\"number\" class=\"input validator w-full\" min=\"1\" placeholder=\"1\" required value><p class=\"validator-hint\">>= 1 </p></div></fieldset><div class=\"modal-action\"><button class=\"btn btn-primary mt-1\" type=\"submit\">Create</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func NewProjectModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<dialog id=\"project_modal\" class=\"modal\"><div class=\"modal-box\"><h3 class=\"text-lg font-bold mb-4\">New project</h3><div class=\"modal-action\"><form method=\"dialog\"><button class=\"btn btn-sm btn-circle btn-ghost absolute right-2 top-2\">✕</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = NewProjectForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><form method=\"dialog\" class=\"modal-backdrop\"><button>close</button></form></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
